// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: record/.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollocDBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Freq          uint32                 `protobuf:"varint,1,opt,name=freq,proto3" json:"freq,omitempty"`
	Avgdist       int32                  `protobuf:"varint,2,opt,name=avgdist,proto3" json:"avgdist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollocDBEntry) Reset() {
	*x = CollocDBEntry{}
	mi := &file_record__proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollocDBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollocDBEntry) ProtoMessage() {}

func (x *CollocDBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_record__proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollocDBEntry.ProtoReflect.Descriptor instead.
func (*CollocDBEntry) Descriptor() ([]byte, []int) {
	return file_record__proto_rawDescGZIP(), []int{0}
}

func (x *CollocDBEntry) GetFreq() uint32 {
	if x != nil {
		return x.Freq
	}
	return 0
}

func (x *CollocDBEntry) GetAvgdist() int32 {
	if x != nil {
		return x.Avgdist
	}
	return 0
}

type TokenDBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Freq          uint32                 `protobuf:"varint,1,opt,name=freq,proto3" json:"freq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDBEntry) Reset() {
	*x = TokenDBEntry{}
	mi := &file_record__proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDBEntry) ProtoMessage() {}

func (x *TokenDBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_record__proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDBEntry.ProtoReflect.Descriptor instead.
func (*TokenDBEntry) Descriptor() ([]byte, []int) {
	return file_record__proto_rawDescGZIP(), []int{1}
}

func (x *TokenDBEntry) GetFreq() uint32 {
	if x != nil {
		return x.Freq
	}
	return 0
}

var File_record__proto protoreflect.FileDescriptor

const file_record__proto_rawDesc = "" +
	"\n" +
	"\rrecord/.proto\x12\x06colloc\"=\n" +
	"\rCollocDBEntry\x12\x12\n" +
	"\x04freq\x18\x01 \x01(\rR\x04freq\x12\x18\n" +
	"\aavgdist\x18\x02 \x01(\x05R\aavgdist\"\"\n" +
	"\fTokenDBEntry\x12\x12\n" +
	"\x04freq\x18\x01 \x01(\rR\x04freqB\x06Z\x04./pbb\x06proto3"

var (
	file_record__proto_rawDescOnce sync.Once
	file_record__proto_rawDescData []byte
)

func file_record__proto_rawDescGZIP() []byte {
	file_record__proto_rawDescOnce.Do(func() {
		file_record__proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record__proto_rawDesc), len(file_record__proto_rawDesc)))
	})
	return file_record__proto_rawDescData
}

var file_record__proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_record__proto_goTypes = []any{
	(*CollocDBEntry)(nil), // 0: colloc.CollocDBEntry
	(*TokenDBEntry)(nil),  // 1: colloc.TokenDBEntry
}
var file_record__proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_record__proto_init() }
func file_record__proto_init() {
	if File_record__proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record__proto_rawDesc), len(file_record__proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record__proto_goTypes,
		DependencyIndexes: file_record__proto_depIdxs,
		MessageInfos:      file_record__proto_msgTypes,
	}.Build()
	File_record__proto = out.File
	file_record__proto_goTypes = nil
	file_record__proto_depIdxs = nil
}
